#!/usr/bin/env python3
"""Генерирует src/challenge_blob.rs — встраивает челлендж-бинари в приложение."""
import os
LAB = os.path.join(os.path.dirname(__file__), '..', 'assets', 'challenges')
OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'challenge_blob.rs')
entries = []
for f in sorted(os.listdir(LAB)):
    p = os.path.join(LAB, f)
    if os.path.isfile(p) and (f.endswith('.exe') or '.' not in f):
        entries.append((f, open(p,'rb').read()))
lines = ["// AUTO-GENERATED by tools/gen_embedded.py — do not edit",
         "pub const EMBEDDED_CHALLENGES: &[(&str, &[u8])] = &["]
for name, data in entries:
    hexs = ','.join(f'0x{b:02x}' for b in data)
    lines.append(f'    ("challenges/{name}", &[{hexs}]),')
lines.append("];")
open(OUT,'w').write('\n'.join(lines) + '\n')
print("embedded", len(entries), "files")
